-- Generated by Mocodo 4.0.14

CREATE TABLE Client (
  PRIMARY KEY (numero_client),
  numero_client VARCHAR(42) NOT NULL,
  prenom        VARCHAR(42),
  nom           VARCHAR(42),
  adresse       VARCHAR(42)
);

CREATE TABLE COMMANDE (
  PRIMARY KEY (id_commande),
  id_commande      VARCHAR(42) NOT NULL,
  statut           VARCHAR(42),
  numero_client    VARCHAR(42) NOT NULL,
  date_de_commande VARCHAR(42)
);

CREATE TABLE COURS (
  PRIMARY KEY (id_cours),
  id_cours VARCHAR(42) NOT NULL,
  intitule VARCHAR(42),
  credits  VARCHAR(42),
  volume   VARCHAR(42)
);

CREATE TABLE ENTREPOT (
  PRIMARY KEY (numero),
  numero  VARCHAR(42) NOT NULL,
  adresse VARCHAR(42)
);

CREATE TABLE EST_STOKE (
  PRIMARY KEY (code_produit, numero),
  code_produit VARCHAR(42) NOT NULL,
  numero       VARCHAR(42) NOT NULL,
  quantite     VARCHAR(42)
);

CREATE TABLE ETUDIANT (
  PRIMARY KEY (numero),
  numero  VARCHAR(42) NOT NULL,
  nom     VARCHAR(42),
  prenom  VARCHAR(42),
  filiere VARCHAR(42)
);

CREATE TABLE INSCRIRE (
  PRIMARY KEY (numero, id_cours),
  numero   VARCHAR(42) NOT NULL,
  id_cours VARCHAR(42) NOT NULL,
  NOTE     VARCHAR(42)
);

CREATE TABLE PRODUIT (
  PRIMARY KEY (code_produit),
  code_produit  VARCHAR(42) NOT NULL,
  libelle       VARCHAR(42),
  prix_unitaire VARCHAR(42),
  type          VARCHAR(42)
);

ALTER TABLE COMMANDE ADD FOREIGN KEY (numero_client) REFERENCES Client (numero_client);

ALTER TABLE EST_STOKE ADD FOREIGN KEY (numero) REFERENCES ENTREPOT (numero);
ALTER TABLE EST_STOKE ADD FOREIGN KEY (code_produit) REFERENCES PRODUIT (code_produit);

ALTER TABLE INSCRIRE ADD FOREIGN KEY (id_cours) REFERENCES COURS (id_cours);
ALTER TABLE INSCRIRE ADD FOREIGN KEY (numero) REFERENCES ETUDIANT (numero);